function BullshitVideoGenerator
music=uigetfile('*.mp3','选择BGM');
if music==0
    music='一剪梅.mp3';
end
[y,Fs]=audioread(music);
BGM=audioplayer(y,Fs);
answer=inputdlg({'我是你们的(      )','我遇到了什么不幸？'},'基本信息',[1 55]);
id=answer{1};
tragedy=answer{2};

greeting=sprintf('%s%s','大家好，我是你们的',id);
sigh='唉';
preApology='我想对大家说一声';
apology='对不起';
hesitation={...
    '这一段时间我一直在犹豫要不要把它说出来',...
    '真的对不起大家，不应该给大家传递负能量的',...
    '这件事情我想了很久'...
    '我知道我的很多粉丝都不会希望我这样做'...
    '相信大家可能已经有预感我要说什么了'...
    '也许这个时候刷到这样的视频真的很令人扫兴'...
    '我只能说，事情发展到今天的地步是谁都不想看到的'...
    };
link='对不起，有些语无伦次了，但是';
changeAttitude={...
    '我真的好累',...
    '我真的撑不住了'...
    '我现在的处境，真的太难了'...
    '我现在真的好难受'...
    '我真的没有坚持下去的动力了'...
    '我经历的一切对我打击太大了'...
    '我只是一个普通人，我也会坚持不住'...
    };
apologyAfresh='对不起，失态了';
announcement=sprintf('%s%s%s%s%s%s','我想说的是，今天，我，',id,',因为',tragedy,',正式退出B站');
background={...
    '我只是一名藉藉无名的小up主',...
    '我曾经也会为三位数的播放量欢欣鼓舞',...
    '我曾经也会不断地刷自己的视频增加播放量',...
    '我曾经也只能仰望着B站的大佬们',...
    '我曾经也会无数遍点开主页，查看播放量',...
    '我很诚实，我也想要关注度'...
    };
effort={...
    '我为了提高自己的视频质量不断努力',...
    '我为了让观众开心不惜每天不吃不喝剪视频',...
    '我为了能够高产，高烧40℃仍然坚持做视频',...
    '我小心翼翼地投稿，就害怕和站内视频撞车',...
    '我珍惜我的观众，每个点赞的人我都会关注他/她/它',...
    '我为了观众开心，不惜冒着被骂蹭热度的风险去改我的标题'...
    };
misfortuneBefalling='但是，这一切，这一切努力，却宛若石沉大海';
excuse='这一切，都是因为某些人';
whatYouHaveDone=sprintf('%s%s%s','正是因为你们，我才会遭遇',tragedy,'!');
detail={...
    '你们整天看着那些低俗的视频，却对我这种真正高质量的视频嗤之以鼻',...
    sprintf('%s\n%s%s','我就只抱怨一句视频没有播放量，你们就私信骂我','诅咒我永远',tragedy),...
    sprintf('%s%s%s','遇到你们之前，我从未想到',tragedy,'会降临在我身上'),...
    sprintf('%s%s','我的视频那么好，你们却因为一点点瑕疵私信我骂我，咒我',tragedy),...
    '我眼睁睁看着，我辛辛苦苦做的视频，被你们某些人喷得一无是处',...
    sprintf('%s%s%s','你们一天天白嫖，就没有想过我会因为这样而遭遇',tragedy,'吗')...
    };
consequenceCell={'都快要抑郁了!','都想要自杀了!','都不想活了!','的生活见不到一点光明!'};
seriousConsequence=sprintf('%s%s','你们知不知道，因为你们，我',consequenceCell{randi(length(consequenceCell))});
shudder='我气得浑身发抖，却无能为力';
failureOfUnderstanding={...
    '我不明白你们为什么要这样对我',...
    '我到底做错了什么',...
    sprintf('%s%s%s','我不能理解为什么我勤勤恳恳、没有做错什么，却只换来了',tragedy,'的结果')...
    '我只是一个小up主，我凭什么会受到这样的不公正'...
    '我不明白为什么我的高质量视频比不上那些粗制滥造的视频',...
    sprintf('%s%s','凭什么那些洋大人可以轻轻松松收获播放量，我作为中国人却只能遭受',tragedy),...
    '那些大up的真的比我的视频好吗，不过是请了水军罢了',...
    '难道现在的人真的只能接受低俗，却欣赏不了我的作品吗'...
    };
calmingDown={...
    '这一段时间，我想了很多',...
    '因为情绪低落，我也看过心理医生',...
    '我尝试接受现实'...
    };
cannotUnderstand='但我还是无法接受这一切';
understandingFinally='直到今天，我想通了';
declaration='我知道，这个地方不再适合我呆下去了，是时候离开了';
finisher={...
    '谢谢大家一路的陪伴',...
    '谢谢你们一直以来的支持',...
    '你们的陪伴给了我力量',...
    '我退出不是因为我肯定那些人的行为，而是因为我真的撑不住了',...
    '我希望我的退出能够让更多人意识到他们的所作所为对我造成的伤害',...
    '地狱空荡荡，魔鬼在人间',...
    '我希望这样的悲剧不会在别人的身上重演'...
    };
farewell=sprintf('%s%s%s','我是',id,'，我们有缘再会');
content={greeting,...
    sigh,...
    preApology,...
    apology,...
    hesitation{randperm(length(hesitation),randi(length(hesitation)))},...
    link,...
    changeAttitude{randperm(length(changeAttitude),randi(length(changeAttitude)))},...
    apologyAfresh,...
    announcement,...
    background{randperm(length(background),randi(length(background)))},...
    effort{randperm(length(effort),randi(length(effort)))},...
    misfortuneBefalling,...
    excuse,...
    whatYouHaveDone,...
    detail{randperm(length(detail),randi(length(detail)))},...
    seriousConsequence,...
    shudder,...
    failureOfUnderstanding{randperm(length(failureOfUnderstanding),randi(length(failureOfUnderstanding)))},...
    calmingDown{randperm(length(calmingDown),randi(length(calmingDown)))},...
    cannotUnderstand,...
    understandingFinally,...
    declaration,...
    finisher{randperm(length(finisher),randi(length(finisher)))},...
    farewell...
    };

screenSize=get(0,'screensize');
hFigure=figure('position',[screenSize(3)/2-540 screenSize(4)/2-360 1080 720],'numbertitle','off','name','Bullshit Video Generator','menubar','none','toolbar','none');
hAxes=axes('parent',hFigure,'units','pixels','position',[1 1 1080 720]);
imgMat=ones(720,1080,3);
imshow(imgMat,'parent',hAxes);
t=timer('executionmode','fixeddelay','period',0.1,'timerfcn',@Renew);
% v=VideoWriter('我宣布正式退出B站.avi');
display=text(540,360,content{1},'horizontalalign','center','verticalalign','middle','fontsize',20,'color',[1 1 1]);
index=1;
upperLimit=length(content)*30;
play(BGM);
% open(v);
start(t);

    function Renew(~,~,~,~,~,~,~)
        if index>upperLimit
            stop(t);
            stop(BGM)
%             close(v);
            return;
        end
        display.String=content{ceil(index/30)};
        display.Color=[1 1 1]/30*(30-mod(index,30));
        index=index+1;
    end

end